CREATE SEQUENCE person_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE tb_person(
    id BIGINT DEFAULT NEXT VALUE FOR person_seq PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone CHAR(13) NOT NULL
);